# Generated by Django 4.2.11 on 2024-04-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocaonota',
            name='tema',
        ),
    ]
