# Generated by Django 4.2.11 on 2024-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloco', '0003_blocaonota_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocaonota',
            name='data_criada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blocaonota',
            name='tema',
            field=models.ManyToManyField(related_name='tema_bloco', to='app_bloco.tema'),
        ),
    ]
