# Generated by Django 4.2.11 on 2024-04-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloco', '0004_alter_blocaonota_data_criada_alter_blocaonota_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocaonota',
            name='tema',
        ),
        migrations.AddField(
            model_name='blocaonota',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tema_bloco', to='app_bloco.tema'),
            preserve_default=False,
        ),
    ]
