# Generated by Django 4.2.11 on 2024-04-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloco', '0005_remove_blocaonota_tema_blocaonota_tema'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlocaoNota',
            new_name='BlocoNota',
        ),
    ]
