# Generated by Django 4.2.11 on 2024-04-27 10:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_bloco', '0006_rename_blocaonota_bloconota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloconota',
            name='conclusao',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
